apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: account-service
  namespace: s652-develop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: account-service
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75