name: .NET Core push on feature branch

on:
  push:
    branches: [feature/*]

jobs:
  build:
    # The virtual machine that will be used on GitHub
    runs-on: ubuntu-18.04
    
    # Run the steps in a Docker container on the virtual machine
    container:
      image: mcr.microsoft.com/dotnet/core/sdk:3.1.201-bionic
    steps:
      # Checkout Git repository
      - uses: actions/checkout@v2

      # Decrypt the gpg encrypted config files
      - name: Decrypt the gpg encrypted config files
        run: ./.github/scripts/decrypt_gpg_passphrase.sh
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPRHASE}}

      # Install the dependencies needed for the project
      - name: Install dependencies
        run: dotnet restore
      
      # Build the project
      - name: Build
        run: dotnet build
      
      # Test the project
      - name: Test
        run: dotnet test